# Generated by Django 5.2.4 on 2025-07-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone')),
                ('subject', models.CharField(max_length=200, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Message')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10, verbose_name='Priority')),
                ('status', models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('replied', 'Replied'), ('closed', 'Closed')], default='new', max_length=10, verbose_name='Status')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name='Subscribed At')),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True, verbose_name='Unsubscribed At')),
            ],
            options={
                'verbose_name': 'Newsletter Subscription',
                'verbose_name_plural': 'Newsletter Subscriptions',
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Al Aqsa School', help_text='The name of your school/institution', max_length=100, verbose_name='Site Name')),
                ('site_tagline', models.CharField(default='Islamic Educational Excellence', help_text='A short tagline describing your institution', max_length=200, verbose_name='Site Tagline')),
                ('site_description', models.TextField(default='Nurturing Islamic character while achieving academic excellence. We provide a comprehensive Islamic education that prepares students for both this world and the hereafter.', help_text='A brief description of your institution', max_length=500, verbose_name='Site Description')),
                ('logo', models.ImageField(blank=True, help_text='Upload your institution logo (recommended size: 200x80px)', null=True, upload_to='site/logo/', verbose_name='Site Logo')),
                ('favicon', models.ImageField(blank=True, help_text='Upload favicon (recommended size: 32x32px)', null=True, upload_to='site/favicon/', verbose_name='Favicon')),
                ('address', models.TextField(default='123 Islamic Street, Dhaka, Bangladesh', help_text='Complete address of your institution', max_length=500, verbose_name='Address')),
                ('phone', models.CharField(default='+880 1234-567890', help_text='Primary contact phone number', max_length=20, verbose_name='Phone Number')),
                ('email', models.EmailField(default='info@alaqsaschool.edu.bd', help_text='Primary contact email address', max_length=254, verbose_name='Email Address')),
                ('emergency_phone', models.CharField(blank=True, help_text='Emergency contact number', max_length=20, null=True, verbose_name='Emergency Phone')),
                ('fax', models.CharField(blank=True, help_text='Fax number if available', max_length=20, null=True, verbose_name='Fax Number')),
                ('office_hours', models.TextField(default='Sunday - Thursday: 8:00 AM - 4:00 PM', help_text='Business/office hours', max_length=200, verbose_name='Office Hours')),
                ('facebook_url', models.URLField(blank=True, help_text='Your Facebook page URL', null=True, verbose_name='Facebook URL')),
                ('twitter_url', models.URLField(blank=True, help_text='Your Twitter profile URL', null=True, verbose_name='Twitter URL')),
                ('instagram_url', models.URLField(blank=True, help_text='Your Instagram profile URL', null=True, verbose_name='Instagram URL')),
                ('youtube_url', models.URLField(blank=True, help_text='Your YouTube channel URL', null=True, verbose_name='YouTube URL')),
                ('linkedin_url', models.URLField(blank=True, help_text='Your LinkedIn profile URL', null=True, verbose_name='LinkedIn URL')),
                ('meta_title', models.CharField(default='Al Aqsa School - Islamic Educational Institution', help_text='SEO title (max 60 characters)', max_length=60, verbose_name='Meta Title')),
                ('meta_description', models.TextField(default='Al Aqsa School provides comprehensive Islamic education with academic excellence. Join us for quality education in a nurturing Islamic environment.', help_text='SEO description (max 160 characters)', max_length=160, verbose_name='Meta Description')),
                ('meta_keywords', models.TextField(blank=True, help_text='SEO keywords (comma-separated)', max_length=500, null=True, verbose_name='Meta Keywords')),
                ('google_analytics_code', models.TextField(blank=True, help_text='Google Analytics tracking code', max_length=500, null=True, verbose_name='Google Analytics Code')),
                ('google_verification_code', models.CharField(blank=True, help_text='Google Search Console verification code', max_length=100, null=True, verbose_name='Google Verification Code')),
                ('copyright_text', models.CharField(default='© 2025 Al Aqsa School. All rights reserved.', help_text='Copyright notice text', max_length=200, verbose_name='Copyright Text')),
                ('privacy_policy_url', models.URLField(blank=True, help_text='URL to privacy policy page', null=True, verbose_name='Privacy Policy URL')),
                ('terms_of_service_url', models.URLField(blank=True, help_text='URL to terms of service page', null=True, verbose_name='Terms of Service URL')),
                ('show_prayer_times', models.BooleanField(default=True, help_text='Display prayer times widget on website', verbose_name='Show Prayer Times')),
                ('prayer_times_api_url', models.URLField(blank=True, help_text='API URL for fetching prayer times', null=True, verbose_name='Prayer Times API URL')),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable the website', verbose_name='Site Active')),
                ('maintenance_mode', models.BooleanField(default=False, help_text='Put website in maintenance mode', verbose_name='Maintenance Mode')),
                ('maintenance_message', models.TextField(blank=True, help_text='Message to display during maintenance', max_length=500, null=True, verbose_name='Maintenance Message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
                'ordering': ['-updated_at'],
            },
        ),
    ]
