# Generated by Django 5.2.4 on 2025-07-13 14:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(default=uuid.uuid4, max_length=36, unique=True),
        ),
    ]
